# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='order_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
