# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0002_auto_20160322_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='number_refills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
