# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0002_remove_allergy_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_app.Patient')),
            ],
        ),
        migrations.AlterField(
            model_name='medication',
            name='dispense_quantity',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage_quantity',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
