# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0003_auto_20160324_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dispense_quantity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
