# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0003_auto_20160323_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='primary_care_physician',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
