# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0004_auto_20160323_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
