# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0004_auto_20160324_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dispense_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
