# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0007_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='current_patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
